version: '3.1'

services:

  db:
    container_name: mysql-db
    image: mysql
    ports:
      - "33061:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quote_db
      MYSQL_USER: quote_user
      MYSQL_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  web:
    container_name: quote-app
    build: .
    image: nbompetsis/quote-web:v0.0.1
    links:
      - db
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      - spring.jpa.hibernate.ddl-auto=none
      - spring.datasource.url=jdbc:mysql://db:3306/quote_db
      - spring.datasource.username=quote_user
      - spring.datasource.password=password
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
      - spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      - spring.sql.init.mode=always
    depends_on:
      db:
        condition: service_healthy
